data_preparation:
  raw_dataset: "data/raw_data"
  raw_dataset_csv: "data/raw_data_csv"
  normalized_dataset_output: "data/normalized"
  windowed_dataset: "data/windows"

training:
  training_dataset: "none yet"